phrase:
  # project_id: 70611176c3b698bd2f886684ae3be9bf
  project_id: a836344dc25f9712bc34750113d89f43
  push:
    sources:
    - file: ./public/locales/en/login.json
      params:
        file_format: i18next
        locale_id: 91f7811d137f2a51adfbcc55753b04aa
        tags: login
        update_translations: true
    - file: ./public/locales/en/dashboard.json
      params:
        file_format: i18next
        locale_id: 91f7811d137f2a51adfbcc55753b04aa
        tags: dashboard
        update_translations: true
    - file: ./public/locales/en/scan.json
      params:
        file_format: i18next
        locale_id: 91f7811d137f2a51adfbcc55753b04aa
        tags: scan
        update_translations: true
    - file: ./public/locales/en/common.json
      params:
        file_format: i18next
        locale_id: 91f7811d137f2a51adfbcc55753b04aa
        tags: common
        update_translations: true
  pull:
    targets:
    - file: ./public/locales/es/login.json
      params:
        file_format: i18next
        locale_id: 45cf35dd006e067e94aff1eb5c860f44
        tags: login
    - file: ./public/locales/es/dashboard.json
      params:
        file_format: i18next
        locale_id: 45cf35dd006e067e94aff1eb5c860f44
        tags: dashboard
    - file: ./public/locales/es/scan.json
      params:
        file_format: i18next
        locale_id: 45cf35dd006e067e94aff1eb5c860f44
        tags: scan
    - file: ./public/locales/es/common.json
      params:
        file_format: i18next
        locale_id: 45cf35dd006e067e94aff1eb5c860f44
        tags: common
