phrase:
  access_token: 7423dsd23
  project_id: 70611176c3
  push:
    sources:
    - file: ./public/locales/<locale_name>/<tag>.json
      params:
        file_format: i18next
  pull:
    targets:
    - file: ./public/locales/<locale_name>/<tag>.json
      params:
        file_format: i18next
