phrase:
  project_id: 70611176c3b698bd2f886684ae3be9bf
  push:
    sources:
    - file: ./public/locales/<locale_name>/<tag>.json
      params:
        file_format: i18next
  pull:
    targets:
    - file: ./public/locales/<locale_name>/<tag>.json
      params:
        file_format: i18next
