# frozen_string_literal: true

# PaymentPlan
class PaymentPlan < ApplicationRecord
  include PrecisionSetable

  belongs_to :user
  belongs_to :land_parcel
  has_many :invoices, dependent: :nullify
  has_many :wallet_transactions, dependent: :nullify

  after_create :generate_monthly_invoices_for_the_year

  enum status: { active: 0, cancelled: 1, deleted: 2 }

  def update_plot_balance(amount, type = 'credit')
    return if amount.zero?

    type.eql?('credit') ? update(plot_balance: plot_balance + amount) : debit_plot_balance(amount)
  end

  def debit_plot_balance(amount)
    if amount > plot_balance
      update(plot_balance: 0, pending_balance: pending_balance + amount - plot_balance)
    else
      update(plot_balance: plot_balance - amount)
    end
  end

  private

  def generate_monthly_invoices_for_the_year
    return if total_amount.nil? || total_amount.zero?

    amount = ((percentage.to_f * total_amount) / 1200)
    (0...12).each { |index| create_invoice_for_month(amount, start_date + index.month) }
  end

  def create_invoice_for_month(amount, date)
    invoices.create!({
                       land_parcel: land_parcel,
                       amount: amount,
                       community: user.community,
                       autogenerated: true,
                       status: 'in_progress',
                       due_date: date + 1.year,
                       user: user,
                     })
  end
end
